=== raniagomaahossny/XML-Labs/Lab1/library.dtd
<!ELEMENT library (location, description, librarian, books)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT librarian (#PCDATA)>
<!ELEMENT books (book+)>
<!ATTLIST books id ID #REQUIRED>
<!ELEMENT book ANY>
<!ELEMENT title (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT preface (#PCDATA)>
<!ELEMENT parts (part+)>
<!ELEMENT part (chapters)>
<!ELEMENT chapters (chapter+)>
<!ELEMENT chapter (title, summary, sections)>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT sections (section+)>
<!ELEMENT section (#PCDATA)>

=== raniagomaahossny/XML-Labs/Lab1/library.xml
<?xml version="1.0"?>
<!DOCTYPE library SYSTEM "library.dtd">

<library>
  <location>down_town_cairo</location>
  <description>This Is A Rania Library</description>
  <librarian>Ms.Mnar</librarian>
  <books id="jj">
    <book>
      <![CDATA[ 
  if (x == 0) {console.log("x is zero");}
  else if (x < 0) {console.log("x is negative");}
  else {console.log("x is positive");}  
  ]]>
      <title>programming</title>
      <ISBN>8880.555.555</ISBN>
      <Author>rania</Author>
      <preface>
        <!-- an introduction to a book, typically stating its subject, scope, or aims. --> ths book is about programming and it is a good book for beginners </preface>
      <parts>
        <part>
          <chapters>
            <chapter>
              <title>what is programming</title>
              <summary>programming is a process of writing a set of instructions to tell a computer
                what to do</summary>
              <sections>
                <section> section 1</section>
                <section> section 2</section>
              </sections>
            </chapter>
            <chapter>
              <title>what is programming</title>
              <summary>programming is a process of writing a set of instructions to tell a computer
                what to do</summary>
              <sections>
                <section> section 1</section>
                <section> section 2</section>
              </sections>
            </chapter>
          </chapters>
        </part>
      </parts>
    </book>
    <book>
      <title>introduction to iot software engineering</title>
      <ISBN>8880.555.8888</ISBN>
      <Author>ryhan</Author>
      <preface>
        <!-- an introduction to a book, typically stating its subject, scope, or aims. --> ths book is about iot programming and it is a good book for beginners </preface>
      <parts>
        <part>
          <chapters>
            <chapter>
              <title>what is programming</title>
              <summary>programming is a process of writing a set of instructions to tell a computer
                what to do</summary>
              <sections>
                <section> section 1</section>
                <section> section 2</section>
              </sections>
            </chapter>
            <chapter>
              <title>what is programming</title>
              <summary>programming is a process of writing a set of instructions to tell a computer
                what to do</summary>
              <sections>
                <section> section 1</section>
                <section> section 2</section>
              </sections>
            </chapter>
          </chapters>
        </part>
      </parts>
    </book>
  </books>
</library>
